// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.6
// source: internal/encoding/tracking.proto

package encoding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tracking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DspId         string                 `protobuf:"bytes,1,opt,name=dsp_id,json=dspId,proto3" json:"dsp_id,omitempty"`
	AdName        string                 `protobuf:"bytes,2,opt,name=ad_name,json=adName,proto3" json:"ad_name,omitempty"`
	BidID         string                 `protobuf:"bytes,3,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracking) Reset() {
	*x = Tracking{}
	mi := &file_internal_encoding_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracking) ProtoMessage() {}

func (x *Tracking) ProtoReflect() protoreflect.Message {
	mi := &file_internal_encoding_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracking.ProtoReflect.Descriptor instead.
func (*Tracking) Descriptor() ([]byte, []int) {
	return file_internal_encoding_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *Tracking) GetDspId() string {
	if x != nil {
		return x.DspId
	}
	return ""
}

func (x *Tracking) GetAdName() string {
	if x != nil {
		return x.AdName
	}
	return ""
}

func (x *Tracking) GetBidId() string {
	if x != nil {
		return x.BidID
	}
	return ""
}

func (x *Tracking) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_internal_encoding_tracking_proto protoreflect.FileDescriptor

var file_internal_encoding_tracking_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64,
	0x69, 0x6e, 0x67, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x67, 0x0a, 0x08,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x73, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x73, 0x70, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x61, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x69, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x69, 0x64, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_encoding_tracking_proto_rawDescOnce sync.Once
	file_internal_encoding_tracking_proto_rawDescData []byte
)

func file_internal_encoding_tracking_proto_rawDescGZIP() []byte {
	file_internal_encoding_tracking_proto_rawDescOnce.Do(func() {
		file_internal_encoding_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_encoding_tracking_proto_rawDesc), len(file_internal_encoding_tracking_proto_rawDesc)))
	})
	return file_internal_encoding_tracking_proto_rawDescData
}

var file_internal_encoding_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_encoding_tracking_proto_goTypes = []any{
	(*Tracking)(nil), // 0: encoding.Tracking
}
var file_internal_encoding_tracking_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_encoding_tracking_proto_init() }
func file_internal_encoding_tracking_proto_init() {
	if File_internal_encoding_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_encoding_tracking_proto_rawDesc), len(file_internal_encoding_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_encoding_tracking_proto_goTypes,
		DependencyIndexes: file_internal_encoding_tracking_proto_depIdxs,
		MessageInfos:      file_internal_encoding_tracking_proto_msgTypes,
	}.Build()
	File_internal_encoding_tracking_proto = out.File
	file_internal_encoding_tracking_proto_goTypes = nil
	file_internal_encoding_tracking_proto_depIdxs = nil
}
